//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson12_ontap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nvt_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nvt_TACGIA()
        {
            this.Nvt_SACH = new HashSet<Nvt_SACH>();
        }
    
        public string Nvt_MaTG { get; set; }
        public string Nvt_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nvt_SACH> Nvt_SACH { get; set; }
    }
}
