//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson12_ontap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nvt_SACH
    {
        public string Nvt_MaSach { get; set; }
        public string Nvt_TenSach { get; set; }
        public Nullable<int> Nvt__SoTrang { get; set; }
        public Nullable<int> Nvt_NamXB { get; set; }
        public string Nvt_MaTG { get; set; }
        public Nullable<bool> Nvt_TrangThai { get; set; }
    
        public virtual Nvt_TACGIA Nvt_TACGIA { get; set; }
    }
}
