//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson12_ontap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NguyenVanThao_2210900125Entities2 : DbContext
    {
        public NguyenVanThao_2210900125Entities2()
            : base("name=NguyenVanThao_2210900125Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nvt_SACH> Nvt_SACH { get; set; }
        public virtual DbSet<Nvt_TACGIA> Nvt_TACGIA { get; set; }
    }
}
